FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Dependences
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    git \
    wget \
    libboost-all-dev \
    pkg-config \
    libglpk-dev \
    && rm -rf /var/lib/apt/lists/*

# HiGHS
#RUN git clone https://github.com/ERGO-Code/HiGHS \
#    && cd HiGHS \
#    && cmake -DFAST_BUILD=ON -DCMAKE_BUILD_TYPE=Release -G Ninja -B build \
#    && cmake --build build \
#    && cmake --install build --strip \
#    && cd ..

# ViennaRNA
COPY --from=satoken/viennarna:latest /usr/local/ /usr/local/
#RUN apt-get update && apt-get install -y \
#    vienna-rna \
#    && rm -rf /var/lib/apt/lists/*

# Directorio de trabajo limpio
WORKDIR /app

# Clonar IPknot
RUN git clone https://github.com/satoken/ipknot.git .

# Compilar (sin HiGHS ni static)
RUN cmake -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_HIGHS=OFF \
          -DSTATIC_BUILD=OFF \
          -G Ninja \
          -B build \
    && cmake --build build \
    && cmake --install build

# Ejecutable por defecto
ENTRYPOINT ["ipknot"]
